version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/bundle
    overwrite: true
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 10
      runas: root
    - location: scripts/start_server.sh
      timeout: 30
      runas: root
