version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/bundle
    overwrite: true
hooks:
  ApplicationStop:
    - location: scritps/stop_server.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scritps/deploy.sh
      timeout: 10
      runas: root
    - location: scritps/start_server.sh
      timeout: 30
      runas: root
